// src/mapper/src/lib/components/editor/editor.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import '$styles/button.css';
	import '$styles/editor.css';
	import { Editor } from '@tiptap/core';
	import StarterKit from '@tiptap/starter-kit';
	import Link from '@tiptap/extension-link';
	import Image from '@tiptap/extension-image';

	import Toolbar from '$lib/components/editor/toolbar.svelte';

	type Props = {
		editable: boolean;
		content: string;
		setEditorHtmlContent?: (content: string) => any;
		setEditorRef?: (editor: any) => void;
	};

	let element: Element | undefined = $state();
	let editor: Editor | undefined = $state();
	let { editable, content, setEditorHtmlContent, setEditorRef }: Props = $props();

	onMount(() => {
		editor = new Editor({
			element: element,
			extensions: [
				StarterKit,
				Link.configure({
					validate: (href: string) => /^https?:\/\//.test(href),
				}),
				Image.configure({
					inline: true,
				}),
			],
			content: content,
			onTransaction: () => {
				editor = editor;
			},
			editable: editable,
			onUpdate: ({ /** editor **/ }) => {
				setEditorHtmlContent && setEditorHtmlContent(editor.getHTML());
			},
		});
		setEditorRef && setEditorRef(editor);
	});

	onDestroy(() => {
		if (editor) {
			editor?.destroy();
		}
	});
</script>

<div class="editor-wrapper">
	<div class="editor ${editable ? 'editable' : 'non-editable'}">
		{#if editor && editable}
			<Toolbar {editor} />
		{/if}

		<div class="bottom">
			<div bind:this={element}></div>
		</div>
	</div>
</div>

// src/frontend/src/components/common/Editor/Editor.tsx
import React, { useState } from 'react';
import { useEditor, EditorContent, FloatingMenu, BubbleMenu } from '@tiptap/react';
import { Toolbar } from '@/components/common/Editor/Toolbar';
import StarterKit from '@tiptap/starter-kit';
import ListItem from '@tiptap/extension-list-item';
import BulletList from '@tiptap/extension-bullet-list';
import OrderedList from '@tiptap/extension-ordered-list';
import Paragraph from '@tiptap/extension-paragraph';
import Text from '@tiptap/extension-text';
import Heading from '@tiptap/extension-heading';
import Document from '@tiptap/extension-document';
import Link from '@tiptap/extension-link';
import Image from '@tiptap/extension-image';
import './editorStyles.scss';

type RichTextEditorProps = {
  editorHtmlContent: string;
  setEditorHtmlContent?: (content: string) => any;
  editable: boolean;
};

const extensions = [
  StarterKit,
  Document,
  Paragraph,
  Text,
  ListItem,
  BulletList,
  OrderedList,
  Heading,
  Link.configure({
    validate: (href) => /^https?:\/\//.test(href),
  }),
  Image.configure({
    inline: true,
  }),
];

const RichTextEditor = ({ editorHtmlContent, setEditorHtmlContent, editable }: RichTextEditorProps) => {
  const editor = useEditor({
    extensions,
    content: editorHtmlContent,
    onUpdate: ({ editor }) => {
      setEditorHtmlContent && setEditorHtmlContent(editor.getHTML());
    },
    editable,
  });

  if (!editor) {
    return null;
  }

  return (
    <div className="fmtm-border-[1px] fmtm-border-gray-300 fmtm-rounded-md fmtm-bg-white">
      {editable && <Toolbar editor={editor} />}
      <EditorContent editor={editor} className={`${editable ? 'fmtm-min-h-[150px]' : 'fmtm-min-h-[50px]'}`} />
    </div>
  );
};

export default RichTextEditor;
