// src/mapper/src/lib/components/pagination.svelte
<script lang="ts">
	import { getPaginationRange, DOTS } from '$lib/utils/getPaginationRange';

	type propsType = {
		showing: number;
		totalCount: number;
		currentPage: number;
		pageSize: number;
		handlePageChange: (value: number) => void;
		isLoading: boolean;
		className: string;
	};

	const { showing, totalCount, currentPage, pageSize, handlePageChange, isLoading, className }: propsType = $props();

	let paginationRange: (number | string)[] = $state([]);
	let currentPageState: number = $state(currentPage);

	$effect(() => {
		paginationRange = getPaginationRange({ currentPage, totalCount, pageSize });
	});

	function handleInputChange(event: Event) {
		let value = +event?.target?.value;
		const maxPage = paginationRange[paginationRange.length - 1] as number;

		if (value > maxPage) value = maxPage;
		if (value < 1) value = 1;

		currentPageState = value;
		handlePageChange(value);
	}
</script>

<div
	class={`bottom-0 flex items-center justify-between flex-col sm:flex-row bg-white py-2 px-11 shadow-black shadow-2xl z-50 gap-1 ${className} box-border`}
>
	<p class="text-[0.75rem] leading-normal font-normal text-grey-800">
		Showing {showing} of {totalCount} results
	</p>

	<div class="flex flex-wrap justify-center gap-x-6 gap-y-1">
		<!-- Go to Page -->
		<div class="flex flex-1 items-center justify-center gap-2 md:pr-6">
			<p class="text-[0.75rem] leading-normal font-normal whitespace-nowrap text-grey-800">Go to Page</p>
			<input
				type="number"
				min="1"
				value={currentPageState}
				disabled={isLoading}
				class="body-md outline-none border border-[#D0D5DD] rounded-lg w-8 h-8 p-1"
				oninput={handleInputChange}
			/>
		</div>

		{#if paginationRange.length > 1}
			<div class="flex items-center gap-2 overflow-x-auto max-sm:w-[100%] max-sm:justify-center">
				<!-- Previous Button -->
				<!-- svelte-ignore a11y_consider_explicit_label -->
				<button
					disabled={currentPage === 1}
					onclick={() => handlePageChange(currentPage - 1)}
					class={`w-5 h-5 min-w-5 min-h-5 rounded-full flex items-center justify-center border-[0px] ${currentPage === 1 ? 'cursor-not-allowed text-[#BDBDBD]' : 'hover:bg-[#FFEDED] duration-100 hover:text-[#B11E20]'}`}
				>
					<hot-icon name="chevron-left" class="!text-[0.8rem] text-[#B11E20] cursor-pointer"></hot-icon>
				</button>

				<!-- Page Numbers -->
				{#each paginationRange as pageNumber}
					{#if pageNumber === DOTS}
						<span class="text-[0.75rem] leading-normal font-normal-regular text-black-600">&#8230;</span>
					{:else}
						<div
							class={`grid h-8 cursor-pointer place-items-center px-3 transition-colors hover:text-primary-900 border-b ${currentPage === pageNumber ? 'border-grey-800' : 'border-white'}`}
							onclick={() => handlePageChange(+pageNumber)}
							onkeydown={(e) => {
								if (e.key === 'Enter') handlePageChange(+pageNumber);
							}}
							role="button"
							tabindex="0"
						>
							<p
								class={`text-[0.75rem] leading-normal font-normal ${currentPage === pageNumber ? 'font-bold text-[#212121]' : 'texy-grey-800'}`}
							>
								{pageNumber}
							</p>
						</div>
					{/if}
				{/each}

				<!-- Next Button -->
				<!-- svelte-ignore a11y_consider_explicit_label -->
				<button
					disabled={currentPage === paginationRange[paginationRange.length - 1]}
					onclick={() => handlePageChange(currentPage + 1)}
					class={`w-5 h-5 min-w-5 min-h-5 rounded-full flex items-center justify-center border-[0px] ${currentPage === paginationRange[paginationRange.length - 1] ? 'cursor-not-allowed text-[#BDBDBD]' : 'hover:bg-[#FFEDED] duration-100 hover:text-[#B11E20]'}`}
				>
					<hot-icon name="chevron-right" class="!text-[0.8rem] text-[#B11E20] cursor-pointer"></hot-icon>
				</button>
			</div>
		{/if}
	</div>
</div>

// src/frontend/src/components/common/Pagination.tsx
import React, { useState } from 'react';
import AssetModules from '@/shared/AssetModules';
import usePagination, { DOTS } from '@/hooks/usePagination';

type paginationPropType = {
  showing: number;
  totalCount: number;
  currentPage: number;
  pageSize: number;
  handlePageChange: (page: number) => void;
  isLoading: boolean;
  className?: string;
};

export default function Pagination({
  showing,
  totalCount,
  currentPage,
  pageSize,
  handlePageChange,
  isLoading,
  className,
}: paginationPropType) {
  const paginationRange = usePagination({
    currentPage,
    totalCount,
    pageSize,
  });

  const [currentPageState, setCurrentPageState] = useState<number | string>(currentPage);

  return (
    <div
      className={`fmtm-bottom-0 fmtm-flex fmtm-items-center fmtm-justify-between fmtm-flex-col sm:fmtm-flex-row fmtm-bg-white fmtm-py-2 fmtm-px-11 fmtm-shadow-black fmtm-shadow-2xl fmtm-z-50 fmtm-gap-1 ${className}`}
    >
      <p className="fmtm-body-sm fmtm-text-grey-800">
        Showing {showing} of {totalCount} results
      </p>

      <div className="fmtm-flex fmtm-flex-wrap fmtm-justify-center fmtm-gap-x-6 fmtm-gap-y-1">
        {/* Go to page */}
        <div className="fmtm-flex fmtm-flex-1 fmtm-items-center fmtm-justify-center fmtm-gap-2 fmtm-md:pr-6">
          <p className="fmtm-body-sm fmtm-whitespace-nowrap fmtm-text-grey-800">Go to Page</p>
          <input
            type="number"
            min={1}
            disabled={isLoading}
            defaultValue={currentPageState}
            value={currentPageState}
            onChange={(e) => {
              const value =
                Number(e.target.value) > (paginationRange[paginationRange.length - 1] as number)
                  ? (paginationRange[paginationRange.length - 1] as number)
                  : +e.target.value;
              setCurrentPageState(value);
              handlePageChange(value);
            }}
            className="fmtm-body-md fmtm-outline-none fmtm-border fmtm-border-[#D0D5DD] fmtm-rounded-lg fmtm-w-8 fmtm-h-8 fmtm-p-1"
          />
        </div>

        {/* pagination-numbers */}
        {paginationRange.length > 1 && (
          <div className="fmtm-flex fmtm-items-center fmtm-gap-2 fmtm-overflow-x-auto fmtm-max-sm:w-[100%] fmtm-max-sm:justify-center">
            {/* previous button */}
            <button
              disabled={currentPage === 1}
              onClick={() => {
                handlePageChange(currentPage - 1);
              }}
              className={`fmtm-w-5 fmtm-h-5 fmtm-min-w-5 fmtm-min-h-5 fmtm-rounded-full fmtm-flex fmtm-items-center fmtm-justify-center ${currentPage === 1 ? 'fmtm-cursor-not-allowed fmtm-text-grey-400' : 'hover:fmtm-bg-red-50 fmtm-duration-100 hover:fmtm-text-red-600'}`}
            >
              <AssetModules.ChevronLeftIcon className="!fmtm-text-sm" />
            </button>

            {/* Page Numbers */}
            {paginationRange.map((pageNumber) => {
              if (pageNumber === DOTS) {
                return (
                  <span key={pageNumber} className="fmtm-body-sm-regular fmtm-text-black-600">
                    &#8230;
                  </span>
                );
              }
              return (
                <div
                  className={`fmtm-grid fmtm-h-8 fmtm-cursor-pointer fmtm-place-items-center fmtm-px-3 fmtm-transition-colors hover:fmtm-text-primary-900 fmtm-border-b ${
                    currentPage === pageNumber ? 'fmtm-border-grey-800' : 'fmtm-border-white'
                  }`}
                  key={pageNumber}
                  onClick={() => {
                    handlePageChange(pageNumber as number);
                  }}
                >
                  <p
                    className={`fmtm-body-sm ${currentPage === pageNumber ? 'fmtm-font-bold fmtm-text-[#212121]' : 'fmtm-texy-grey-800'}`}
                  >
                    {pageNumber}
                  </p>
                </div>
              );
            })}
            {/* next button */}
            <button
              disabled={currentPage === paginationRange[paginationRange.length - 1]}
              onClick={() => {
                handlePageChange(currentPage + 1);
              }}
              className={`fmtm-w-5 fmtm-h-5 fmtm-min-w-5 fmtm-min-h-5 fmtm-rounded-full fmtm-flex fmtm-items-center fmtm-justify-center ${currentPage === paginationRange[paginationRange.length - 1] ? 'fmtm-cursor-not-allowed fmtm-text-grey-400' : 'hover:fmtm-bg-red-50 fmtm-duration-100 hover:fmtm-text-red-600'}`}
            >
              <AssetModules.ChevronRightIcon className="!fmtm-text-sm" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
