// src/frontend/src/components/common/BottomSheet.tsx
import React, { useEffect, useRef, useState } from 'react';
import FmtmLogo from '../../assets/images/hotLog.png';

const BottomSheet = ({ body, onClose }) => {
  const sheetContentRef: any = useRef(null);
  const bottomSheetRef: any = useRef(null);
  const logoRef: any = useRef(null);
  const [startY, setStartY] = useState(0);
  const [startHeight, setStartHeight] = useState(0);
  const [currSheetHeight, setCurrSheetHeight] = useState(0);
  const [show, setShow] = useState(true);
  const [isDragging, setIsDragging] = useState(false);
  const [isFullScreen, setIsFullScreen] = useState(false);

  useEffect(() => {
    setShow(true);
    document.body.style.overflowY = 'hidden';
    bottomSheetRef.current.style.height = `51vh`;
    updateSheetHeight(50);
  }, []);

  const updateSheetHeight = (height) => {
    if (sheetContentRef.current) {
      sheetContentRef.current.style.height = `${height}vh`;
      const top = sheetContentRef.current.getBoundingClientRect().top;
      const logoHeight = logoRef.current.getBoundingClientRect().height;
      logoRef.current.style.top = `${top - logoHeight}px`;
    }
    if (height === 100) {
      setIsFullScreen(true);
    } else {
      setIsFullScreen(false);
    }
  };

  const hideBottomSheet = () => {
    setShow(false);

    onClose();
    document.body.style.overflowY = 'auto';
  };

  const dragStart = (e) => {
    const pagesY = e.pageY || e.changedTouches[0].screenY;
    setStartY(pagesY);
    setStartHeight(parseInt(sheetContentRef.current.style.height));

    setIsDragging(true);
  };

  const dragging = (e) => {
    const delta = startY - (e.pageY || e.changedTouches[0].screenY);
    const newHeight = startHeight + (delta / window.innerHeight) * 100;
    bottomSheetRef.current.style.height = `100vh`;
    updateSheetHeight(newHeight);
  };

  const dragStop = () => {
    let sheetHeight;
    bottomSheetRef.current.style.height = `${currSheetHeight + 1}vh`;

    setIsDragging(false);
    sheetHeight = parseInt(sheetContentRef.current.style.height);
    setCurrSheetHeight(sheetHeight);

    sheetHeight < 25 ? hideBottomSheet() : sheetHeight > 75 ? updateSheetHeight(100) : updateSheetHeight(50);
  };

  useEffect(() => {
    dragStop();
  }, [currSheetHeight]);

  return (
    <div className="fmtm-absolute fmtm-bottom-[200px] fmtm-bg-white sm:fmtm-hidden">
      <div
        className={`bottom-sheet fmtm-fixed fmtm-w-full fmtm-left-0 fmtm-bottom-0 fmtm-flex fmtm-items-center fmtm-flex-col fmtm-justify-end fmtm-duration-100 fmtm-ease-linear ${
          !show ? 'fmtm-opacity-0 fmtm-pointer-events-none' : 'fmtm-opacity-100 fmtm-pointer-events-auto'
        }`}
        ref={bottomSheetRef}
      >
        <div className={`fmtm-fixed fmtm-left-0`} ref={logoRef}>
          <img src={FmtmLogo} alt="Hot Fmtm Logo" className="fmtm-ml-2 fmtm-z-10 fmtm-w-[5.2rem]  fmtm-mb-4" />
        </div>
        <div
          ref={sheetContentRef}
          className={`bottom-sheet-content fmtm-shadow-[30px_-10px_10px_5px_rgba(0,0,0,0.1)] fmtm-w-full fmtm-relative fmtm-bg-white fmtm-max-h-[100vh] fmtm-h-[50vh] fmtm-max-w-[1150px] fmtm-py-6 fmtm-px-4 fmtm-duration-300 fmtm-ease-in-out fmtm-overflow-hidden ${
            !show ? 'fmtm-translate-y-[100%]' : 'fmtm-translate-y-[0%]'
          } ${isDragging ? 'fmtm-transition-none' : ''} ${isFullScreen ? 'fmtm-rounded-none' : 'fmtm-rounded-t-2xl'}`}
        >
          <div className="header fmtm-flex fmtm-justify-center">
            <div
              className="drag-icon fmtm-cursor-grab fmtm-select-none fmtm-p-4 -fmtm-mt-4 fmtm-z-[9999]"
              onMouseDown={dragStart}
              onTouchStart={dragStart}
              onMouseMove={dragging}
              onTouchMove={dragging}
              onMouseUp={dragStop}
              onTouchEnd={dragStop}
            >
              <span className="fmtm-h-1 fmtm-w-[2.5rem] fmtm-block fmtm-bg-[#c7d0e1] fmtm-rounded-full hover:fmtm-bg-primaryRed"></span>
            </div>
          </div>
          <div className="body fmtm-overflow-y-scroll scrollbar fmtm-h-full fmtm-p-[1px]">{body}</div>
        </div>
      </div>
    </div>
  );
};

export default BottomSheet;

// src/mapper/src/lib/components/common/bottom-sheet.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let bottomSheetRef: any;
	let sheetContentRef: any;

	let startY: number;
	let startHeight: number;
	let currSheetHeight: number;
	let show: boolean;
	let isDragging: boolean = false;

	export let onClose: () => void;

	const updateSheetHeight = (height: number) => {
		if (sheetContentRef) {
			sheetContentRef.style.height = `${height}vh`;
		}
	};

	onMount(() => {
		show = true;
		document.body.style.overflowY = 'hidden';
		bottomSheetRef.style.height = `50vh`;
		updateSheetHeight(50);
	});

	const hideBottomSheet = () => {
		show = false;
		onClose();
		document.body.style.overflowY = 'auto';
	};

	const dragStart = (e) => {
		e.preventDefault();
		const pagesY = e.pageY || e.changedTouches[0].screenY;
		startY = pagesY;
		startHeight = parseInt(sheetContentRef.style.height);
		isDragging = true;
	};

	const dragging = (e) => {
		if (!isDragging) return;
		const delta = startY - (e.pageY || e.changedTouches[0].screenY);
		const newHeight = startHeight + (delta / window.innerHeight) * 100;
		bottomSheetRef.style.height = `100vh`;
		updateSheetHeight(newHeight);
	};

	const dragStop = () => {
		let sheetHeight;
		bottomSheetRef.style.height = `${currSheetHeight + 1}vh`;

		isDragging = false;
		sheetHeight = parseInt(sheetContentRef.style.height);
		currSheetHeight = sheetHeight;

		if (sheetHeight < 25) {
			hideBottomSheet();
		} else if (sheetHeight <= 75) {
			updateSheetHeight(50);
		} else {
			updateSheetHeight(85);
		}
	};

	$: if (currSheetHeight) {
		dragStop();
	}
</script>

<div>
	<!-- sheet container -->
	<div
		bind:this={bottomSheetRef}
		class={`z-10 bottom-sheet fixed w-[100vw] left-0 bottom-0 flex items-center flex-col justify-end duration-100 ease-linear z-20 ${
			!show ? 'opacity-0 pointer-events-none' : 'opacity-100 pointer-events-none'
		}`}
	>
		<!-- sheet content -->
		<div
			style="border-top-left-radius: 25px; border-top-right-radius: 25px;"
			bind:this={sheetContentRef}
			class={`bottom-sheet-content shadow-[0px_-10px_10px_5px_rgba(0,0,0,0.05)] w-full relative bg-white max-h-[100vh] h-[50vh] max-w-[100vw] pb-6 duration-300 ease-in-out overflow-hidden md:max-w-[900px] ${
				!show ? 'translate-y-[100%]' : 'translate-y-[0%] pointer-events-auto'
			} ${isDragging ? 'transition-none' : ''}`}
		>
			<div
				style={' border-top-left-radius: 1rem;'}
				class="flex justify-center py-4 sm:py-8 cursor-grab select-none w-full"
				on:mousedown={dragStart}
				on:touchstart={dragStart}
				on:mousemove={dragging}
				on:touchmove={dragging}
				on:touchend={dragStop}
				on:mouseup={dragStop}
				on:mouseout={dragStop}
			>
				<span class="h-[6px] w-[3.25rem] block bg-[#d2d2d4] rounded-full pointer-events-none hover:bg-green-400"></span>
			</div>
			<!-- </div> -->

			<!-- body -->
			<div class="overflow-y-scroll scrollbar h-[calc(100%-5rem)] sm:h-[calc(100%-6.7rem)] px-4">
				<slot />
			</div>
		</div>
	</div>
</div>
