// src/frontend/src/components/home/ProjectCardSkeleton.tsx
import React from 'react';
import { Skeleton } from '@/components/common/Skeleton';

// Skeleton card main purpose is to perform loading in case of any delay in retrieving project
const ProjectCardSkeleton = ({ className }: { className?: string }) => {
  return Array.from({ length: 12 }).map((_, i) => (
    <div
      key={i}
      className={`fmtm-h-[15.5rem] fmtm-bg-white fmtm-rounded-lg fmtm-p-4 fmtm-flex fmtm-flex-col fmtm-justify-between ${className}`}
    >
      <div>
        <Skeleton className="fmtm-w-8 fmtm-h-8 !fmtm-rounded-full" />
        <div className="fmtm-my-3">
          <Skeleton className="fmtm-w-8 fmtm-h-[14px] !fmtm-rounded-full fmtm-mb-1" />
          <Skeleton className="fmtm-w-[80px] fmtm-h-[14px] !fmtm-rounded-full" />
        </div>
        <Skeleton className="fmtm-w-14 fmtm-h-[14px] !fmtm-rounded-full fmtm-mb-1" />
        <Skeleton className="fmtm-w-full fmtm-h-[14px] !fmtm-rounded-full" />
        <Skeleton className="fmtm-w-full fmtm-h-[14px] !fmtm-rounded-full fmtm-my-1" />
        <Skeleton className="fmtm-w-[50%] fmtm-h-[14px] !fmtm-rounded-full" />
      </div>

      <div>
        <div className="fmtm-flex fmtm-items-center fmtm-justify-between fmtm-mb-1">
          <Skeleton className="fmtm-w-10 fmtm-h-[14px] !fmtm-rounded-full" />
          <Skeleton className="fmtm-w-16 fmtm-h-[14px] !fmtm-rounded-full" />
        </div>
        <Skeleton className="fmtm-w-full fmtm-h-[6px] !fmtm-rounded-full" />
      </div>
    </div>
  ));
};
export default ProjectCardSkeleton;

// src/mapper/src/lib/components/project-summary/project-card-skeleton.svelte
<script>
	import Skeleton from '$lib/components/skeleton.svelte';
</script>

<div class="box-border h-[16rem] bg-white rounded-lg p-4 flex flex-col justify-between rounded-lg">
	<div>
		<Skeleton className="w-8 h-8 !rounded-full" />
		<div class="my-3">
			<Skeleton className="w-8 h-[14px] !rounded-full mb-1" />
			<Skeleton className="w-[80px] h-[14px] !rounded-full" />
		</div>
		<Skeleton className="w-14 h-[14px] !rounded-full mb-1" />
		<Skeleton className="w-full h-[14px] !rounded-full" />
		<Skeleton className="w-full h-[14px] !rounded-full my-1" />
		<Skeleton className="w-[50%] h-[14px] !rounded-full" />
	</div>

	<div>
		<div class="flex items-center justify-between mb-1">
			<Skeleton className="w-10 h-[14px] !rounded-full" />
			<Skeleton className="w-16 h-[14px] !rounded-full" />
		</div>
		<Skeleton className="w-full h-[6px] !rounded-full" />
	</div>
</div>
